# Generated by Django 3.1.7 on 2021-04-11 12:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='slider')),
                ('description', ckeditor.fields.RichTextField()),
                ('status', models.BooleanField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='settingmodel',
            options={'verbose_name': 'setting'},
        ),
    ]
