# Generated by Django 3.1.7 on 2021-04-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210411_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='is_first',
            field=models.BooleanField(default=0),
        ),
    ]
