# Generated by Django 3.1.7 on 2021-04-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_slider_is_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='is_first',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1),
        ),
    ]
