# Generated by Django 3.1.7 on 2021-04-29 08:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210422_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognews',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 4, 29, 8, 36, 47, 756322, tzinfo=utc)),
        ),
    ]
